import type { Metadata } from "next";
import "./globals.css";
import { Inter, Jost } from "next/font/google";
import Nav from "./components/Nav";

const jost = Jost({
  subsets: ['latin'],
  variable: "--font-brand",
  weight: "variable"
})

const inter = Inter({
  subsets: ['latin'],
  variable: "--font-app",
  weight: "variable"
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${jost.variable} ${inter.variable} flex flex-col items-center antialiased pt-4`}
      >
      	<Nav />
        {children}
      </body>
    </html>
  );
}
